### ISSUE TITLE
Remove constants from `wp-config.php`

### ISSUE THREAD

**Issue by Plou** [dummy-team/wp-dummy-twig#22]
Cache & debug constant are already defined in wp-config. We should only define them in the local config.

``` php 
define('WP_DEBUG', false);
define('WP_CACHE, false);
```

**Comment by Gregcop1** [comment]
use the composer install ;) with it, you build your wp-config depending on your environment ;)

**Comment by Plou** [comment]
Anyway the wp-config is in the wordpress install, not in the theme.
