### ISSUE TITLE
Rename `lib` to `configuration` ?

### ISSUE THREAD

**Issue by Plou** [dummy-team/wp-dummy-twig#27]

**Comment by FeetloveR** [comment]
+1

**Comment by toofff** [comment]
:+1:

**Comment by shatimes** [comment]
Done

**Comment by toofff** [comment]
@shatimes which is what it's done? I see no commit or pull request.

**Comment by shatimes** [comment]
Now It's really done ;-)

**Comment by toofff** [comment]
👍 

@shatimes 
For open issues, it would be nice to do pull request that we can validate later.

We can read and avoid some bug. We can be aware of what you do, and to follow the project.

**Comment by Gregcop1** [comment]
You can use `Fix #IDOfAnIssue` in the comment of your commit or the description of the PR to auto-close the issue. The advantage here is that github automatically create links between issue and commit to allow better navigation and interaction.
