### ISSUE TITLE
Travis + PHP CS Fixer

### ISSUE THREAD

**Issue by toofff** [dummy-team/wp-dummy-twig#42]
Establish Travis with php CS Fix?

I can do it.

**Comment by Plou** [comment]
that's sound nice, but I'm not sure wordpress will pass PSR coding standards.

**Comment by toofff** [comment]
This is the php, the basic standards pass for everyone.

**Comment by Gregcop1** [comment]
If it's just for php cs, the ide can fix this on save no ? (if phpstorm can, I think other ide can too)

**Comment by toofff** [comment]
@Gregcop1 For you it is useless to put Travis on the project?

**Comment by Gregcop1** [comment]
if it's just for PHPCS, Travis is useless (IDE do the job), but I you write some tests (for your autoload script for example), it may be usefull
