### ISSUE TITLE
Rework functions.php structure

### ISSUE THREAD

**Issue by Plou** [dummy-team/wp-dummy-twig#7]
Replace some functions by an include

**Comment by Plou** [comment]
An exemple of `autoload.php` can be found in the alfa theme.

**Comment by Plou** [comment]
I've grouped methods from functions.php, names are copy/paste, we'll have to find explicit names for folders and files
For the function structure, I'm thinking about something like that:

```
function.php
 - include configuration
 - include shortcodes
 - new TimberSite()

configuration

  -- theme support
    -- add_theme_support.php

  -- mce
    -- add_mce_buttons_2.php
    -- tiny_mce_before_init.php
    -- add_editor_styles.php
    
  -- posttypes
    -- register_post_types.php

  -- taxonomies
    -- register_taxonomies.php

  -- menus
    -- main.php
    -- footer.php

  -- context
    -- add_to_context.php

  -- register_scripts
   -- css.php
   -- js.php

  -- twig
    -- add_to_twig.php
```

**Comment by Gregcop1** [comment]
It seems great

**Comment by Plou** [comment]
To ease Menu registration I tested this

``` php
// functions.php
class StarterSite extends TimberSite {
  public function __construct() {
    new DummyMenu('main', __('Menu principal', 'skin-dummy'), $context);
  }
}

// DummyMenu.php
  class DummyMenu
  {
    public function __construct( $id, $description , $context) {
      $this->id = $id;
      $this->description = $description;

      add_action( 'init', array($this, 'register_menu') );
      add_filter( 'timber_context', array($this, 'add_to_context' ) );
    }

    public function register_menu() {
      register_nav_menu( $this->id, $this->description );
    }

    public function add_to_context( $context ) {
      if (!isset($context['menu'])) {
        $context['menu'] = array();
      }
      $context['menu'][$this->id] = new TimberMenu($this->id);
      return $context;
    }
  }
```

**Comment by shatimes** [comment]
To complete Plou's proposal : 

-inc
   ---editor
      --add_buttons.php
      --add_editor_stylesheet.php
      --styles.php

   ---menus
      --main.php
      --footer.php

   ---post_types
      --event.php

   ---register_scripts
      --css.php
      --js.php

   ---shortcodes
   -----enable
   -------in_list_posts

   ---taxonomies
      --event-category.php

   ---theme_support
       --add_theme_support.php

   ---timber
       --add_to_context.php
       --add_to_twig.php

**Comment by Plou** [comment]
If we manage to get a working structure, it could be possible to have external components.
I have in mind a Event taxonomie with post type registration and basic twig template. To integrate it we'd only need to copy a twig folder `Event` and the php registration files `inc/post_types/event.php`.

**Comment by Gregcop1** [comment]
You've lost me @Plou but may be it's cause i'm not fully involve actually in twig requirement.


Finally, I don't think name like add_to... are good. It's the name of the function that is used... What happen if the function change or if you wan't to use many functions ???
I prefer : 
```
-- timber
     -- context
     -- twig
```
Directories should represent *a category* and files *a feature*
BTW I think it's more common to have a **lib** directory than a **inc**. Commonly, **vendor** is used for third party library and **lib** for project libraries

**Comment by Plou** [comment]
The first and main problem to solve is to split function.php in many files.

**Comment by Plou** [comment]
I'm closing this issue as @jviste solved it. For further improvement to the php structure create a specific issue.
